[phases.setup]
nixPkgs = ["rust", "cargo", "pkg-config", "openssl"]

[phases.build]
cmds = ["cd backend && cargo build --release"]

[phases.start]
cmd = "cd backend && ./target/release/backend"

[variables]
RUST_VERSION = "1.75.0"
