[phases.setup]
nixPkgs = ["rust", "cargo", "pkg-config", "openssl"]

[phases.install]
cmds = []

[phases.build]
cmds = ["cargo build --release"]

[phases.start]
cmd = "./target/release/backend"

[variables]
RUST_VERSION = "1.75.0"
